### ISSUE TITLE
Local dev broken, missing transcripts & videos

### ISSUE THREAD

**Issue by Whoaa512** [zcaceres/fastai-video-browser#24]
I was going to start adding some features but realized that the transcripts and videos are missing.

Are there any scripts we can commit to grab the necessary data for development?

**Comment by zcaceres** [comment]
sorry about that @Whoaa512 . We are in a slightly strange place because Jeremy asked me not to commit/publicly share the videos until after the course. What's your fastai forum name? I'll send you how to get them.

**Comment by Whoaa512** [comment]
No worries, my fastai forum name is cjwinslow

**Comment by zcaceres** [comment]
resolved
